name: Docker Build
description: 'Build a Docker image for the Quarkus application'

inputs:
  tag:
    description: 'The tag for the Docker image'
    required: true
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Create Docker Image
      run: docker build . --file src/main/docker/Dockerfile.jvm  --tag academy:${{ inputs.tag }}
      shell: bash
    - name: List Docker Images
      run: docker image list
      shell: bash