name: Docker Push
description: 'Push a Docker image to the Dockerhub'

inputs:
  DOCKERHUB_USERNAME:
    description: 'The username for the Dockerhub'
    required: true
  DOCKERHUB_TOKEN:
    description: 'The token for the Dockerhub'
    required: true
  path_dockerfile:
    description: 'The tag for the Docker image'
    required: true
    default: 'Dockerfile'
  image_name:
    description: 'The name for the Docker image'
    required: true
    default: 'academy'
  tag_name:
    description: 'The tag for the Docker image'

runs:
  using: composite
  steps:
    - name: Docker Build
      uses: ./.github/actions/docker_build
      with:
          path_dockerfile: ${{ inputs.path_dockerfile }}
          image_name: ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}
          tag_name: ${{ inputs.tag_name }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push  ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash