name: Docker Push
description: 'Push a Docker image to the Dockerhub'

inputs:
  DOCKERHUB_USERNAME:
    description: 'The username for the Dockerhub'
    required: true
  DOCKERHUB_TOKEN:
    description: 'The token for the Dockerhub'
    required: true

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash